### ISSUE TITLE
找不到puppeteer.js和Renderer.js

### ISSUE THREAD

**Issue by Proito666** [Qz-Sean/avocado-plugin#1]
utils/puppeteer.js里引的Puppeteer和Renderer找不到。
Puppeteer路径改成‘../../../lib/puppeteer/puppeteer.js’可以了，Renderer好像没有

**Comment by ikechan8370** [comment]
Renderer是喵崽的写法，等作者兼容Yunzai和喵崽吧

**Comment by Proito666** [comment]
ok我把喵崽的文件拷过来试试

**Comment by Proito666** [comment]
> Renderer是喵崽的写法，等作者兼容Yunzai和喵崽吧



> Renderer是喵崽的写法，等作者兼容Yunzai和喵崽吧

ok我把喵崽的文件拷过来试试

**Comment by Proito666** [comment]
> Renderer是喵崽的写法，等作者兼容Yunzai和喵崽吧

ok我把喵崽的文件拷过来试试

**Comment by Qz-Sean** [comment]
> utils/puppeteer.js里引的Puppeteer和Renderer找不到。 Puppeteer路径改成‘../../../lib/puppeteer/puppeteer.js’可以了，Renderer好像没有

已做适配，但效果可能不是很好。嗯！建议用喵崽！
