### ISSUE TITLE
url识别异常的时候会导致内存占用飙高

### ISSUE THREAD

**Issue by 127Wzc** [Qz-Sean/avocado-plugin#2]
今天刚装的这个插件，出现这个超时后 就会出现内存飙高不减 导致机器卡死
![image](https://github.com/Qz-Sean/avocado-plugin/assets/52766844/aee87dd2-1746-46c6-9167-de567206f6ad)

**Comment by 127Wzc** [comment]
> 今天刚装的这个插件，出现这个超时后 就会出现内存飙高不减 导致机器卡死 ![image](https://user-images.githubusercontent.com/52766844/249099440-aee87dd2-1746-46c6-9167-de567206f6ad.png)
机器为两核4g。常驻内存占用在2g左右  出现这个异常后直飙占用60飙到90+ 一直不下

**Comment by Qz-Sean** [comment]
> > 今天刚装的这个插件，出现这个超时后 就会出现内存飙高不减 导致机器卡死 ![image](https://user-images.githubusercontent.com/52766844/249099440-aee87dd2-1746-46c6-9167-de567206f6ad.png)
> > 机器为两核4g。常驻内存占用在2g左右  出现这个异常后直飙占用60飙到90+ 一直不下

收到！我瞅瞅

**Comment by Qz-Sean** [comment]
> > 今天刚装的这个插件，出现这个超时后 就会出现内存飙高不减 导致机器卡死 ![image](https://user-images.githubusercontent.com/52766844/249099440-aee87dd2-1746-46c6-9167-de567206f6ad.png)
> > 机器为两核4g。常驻内存占用在2g左右  出现这个异常后直飙占用60飙到90+ 一直不下

更新试试

**Comment by 127Wzc** [comment]
> > > 今天刚装的这个插件，出现这个超时后 就会出现内存飙高不减 导致机器卡死 ![image](https://user-images.githubusercontent.com/52766844/249099440-aee87dd2-1746-46c6-9167-de567206f6ad.png)
> > > 机器为两核4g。常驻内存占用在2g左右  出现这个异常后直飙占用60飙到90+ 一直不下
> 
> 更新试试
 这半天使用下来已经正常了
