### ISSUE TITLE
如何关闭自动撤回？

### ISSUE THREAD

**Issue by AirKeen76** [Qz-Sean/avocado-plugin#5]
如题，例如预览网址失败时的提示信息会在几秒后自动撤回，那么我要更改哪里才不会自动撤回呢

**Comment by Qz-Sean** [comment]
![image](https://github.com/Qz-Sean/avocado-plugin/assets/56262913/8374c2f1-7b21-4389-88e2-8c15147b3ca3)
![image](https://github.com/Qz-Sean/avocado-plugin/assets/56262913/dca74679-f2ce-4d97-85ac-479181da8a93)
改成 `await e.reply([url, '\n', img])`

**Comment by AirKeen76** [comment]
谢谢喵，解决啦
